In [1]:
from google.colab import files
uploaded=files.upload()

Saving iris.xls to iris.xls


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
path="/content/iris.xls"
df=pd.read_excel(path)
df.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [4]:
#1.read the dataset to python environment
df.tail()

SL   SW   PL   PW  Classification
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  NaN  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
print(df.shape)

(150, 5)


In [7]:
df.describe()

SL          SW          PL          PW
count  143.000000  144.000000  144.000000  150.000000
mean     5.855944    3.049306    3.756250    1.198667
std      0.828168    0.430644    1.761306    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [8]:
#2. Do the necessary pre-processing steps
# Separate features and target variable
X = df.iloc[:, :-1] # Features
y = df.iloc[:, -1] # Target variable

# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform feature scaling (optional, but can be beneficial for some algorithms)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
from sklearn.impute import SimpleImputer

# Create an instance of the SimpleImputer with the desired strategy
imputer = SimpleImputer(strategy='mean') 

# Fit the imputer on the training data and transform both the training and testing data
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)
print(X_train)
print(X_test)

[[-1.49718305e+00  1.24168128e+00 -1.57548762e+00 -1.30948358e+00]
 [-1.60907217e-01  3.05354261e+00 -1.28707457e+00 -1.04292204e+00]
 [ 1.05388899e+00  1.09267953e-01  3.85721101e-01  2.89885679e-01]
 [-1.25422381e+00  7.88715952e-01 -1.22939196e+00 -1.30948358e+00]
 [-1.74014229e+00  3.35750619e-01 -1.31295940e-16 -1.30948358e+00]
 [ 5.67970509e-01 -1.24962804e+00  7.31816757e-01  9.56289538e-01]
 [ 0.00000000e+00  3.35750619e-01  4.43403710e-01  4.23166451e-01]
 [-7.68305322e-01  8.72596342e-16 -1.28707457e+00 -1.30948358e+00]
 [-1.01126456e+00  1.24168128e+00 -1.34475718e+00 -1.30948358e+00]
 [-7.68305322e-01  2.37409462e+00 -1.28707457e+00 -1.44276436e+00]
 [-3.94275963e-02 -7.96662712e-01  7.89499366e-01  9.56289538e-01]
 [ 0.00000000e+00  7.88715952e-01  4.43403710e-01  5.56447222e-01]
 [ 1.05388899e+00  1.09267953e-01  5.58768929e-01  4.23166451e-01]
 [-5.25346080e-01  1.92112928e+00 -1.40243979e+00 -1.04292204e+00]
 [-5.25346080e-01  8.72596342e-16 -1.28707457e+00 -1.30948358e

In [10]:
#3. Find out which classification model gives the best result 
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


# Define the models to evaluate
models = [
    ('Logistic Regression', LogisticRegression()),
    ('Decision Tree', DecisionTreeClassifier()),
    ('K-Nearest Neighbors', KNeighborsClassifier()),
    ('Support Vector Machine', SVC()),
    ('Random Forest', RandomForestClassifier())
]

# Evaluate each model using cross-validation
for name, model in models:
    scores = cross_val_score(model, X_train, y_train, cv=5)
    print(f'{name}: Mean accuracy = {scores.mean():.4f}, Standard deviation = {scores.std():.4f}')

Logistic Regression: Mean accuracy = 0.9500, Standard deviation = 0.0808
Decision Tree: Mean accuracy = 0.9333, Standard deviation = 0.0333
K-Nearest Neighbors: Mean accuracy = 0.9417, Standard deviation = 0.0204
Support Vector Machine: Mean accuracy = 0.9583, Standard deviation = 0.0456
Random Forest: Mean accuracy = 0.9583, Standard deviation = 0.0456
